config/routes.rb
Rails.application.routes.draw do
	  root 'gossips#index'
	  resources :gossips
end

 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

	def new
		@gossip = Gossip.new
	end

	def create
		@gossip = Gossip.new(gossip_params)
		if @gossip.save
  		redirect_to @gossip
  	else
  		render.new
  	end
	end

	def show
  	@gossip = Gossip.find(params[:id])
	end

	def edit
		@gossip = Gossip.find(params[:id])
	end

	def update
		@gossip = Gossip.find(params[:id])
		if @gossip.save
			redirect_to @gossip
		else
			render "new"
		end
	end

	def destroy
		@gossip = Gossip.find(params[:id])
		@gossip.destroy
		redirect_to gossips_path
	end

	def index
		@gossips = Gossip.all
	end
		
	private

	def gossip_params
		params.permit(:anonymous_author, :content)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/views/gossips/_form.html.erb
<% if @gossip.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@gossip.errors.count, "error") %> prohibited
        this gossip from being saved:
      </h2>
      <ul>
        <% @gossip.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

	<%= label_tag 'Author', "Author du gossip" %> 
	<%= text_field_tag 'author' %> 

	<%= label_tag 'string', 'Content' %> 
	<%= text_area_tag 'string' %>

app/views/gossips/edit.html.erb
<h1>Editer le gossip</h1>


<%= form_tag gossips_path(@gossip), method: :put do %>
  <%= render 'form' %>
	<%= submit_tag "Modifier ton gossip !"%> 
<% end %>

<%= link_to 'Clique pour détruire', @gossip, method: :delete %>

app/views/gossips/index.html.erb
<h1>Listing des gossips</h1>
 
<table>
  <tr>
    <th>Author</th>
    <th>Content</th>
  </tr>
 
  <% @gossips.each do |gossip| %>
    <tr>
      <td><%= gossip.anonymous_author %></td>
      <td><%= gossip.content %></td>
      <td><%= link_to "Aller sur le gossip", gossip_path(gossip) %></td>
      <td><%= link_to "Editer le gossip",
      edit_gossip_path(gossip) %></td> 
       <td><%= link_to 'Destroy', gossip_path(gossip),
                method: :delete,
                data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to 'Créer un nouveau gossip', new_gossip_path %></p>

app/views/gossips/new.html.erb
<h1> Lancer un nouveau gossip</h1>

<%= form_tag (gossips_path) do %>
<%= label_tag 'anonymous_author', "Votre pseudo de délateur" %>
<%= text_field_tag 'anonymous_author' %>
<br>
<%= label_tag 'content', 'La rumeur à balancer' %>
<%= text_area_tag 'content' %>
<br><br>
<%= submit_tag "Lancer !"%>
<% end %>

app/views/gossips/show.html.erb
<p>
  <strong>Author</strong>
  <%= @gossip.anonymous_author %>
</p>
 
<p>
  <strong>Gossip:</strong>
  <%= @gossip.content %>
</p>


<p><%= link_to 'Revenir à la liste des gossips', gossips_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>